#Requires -Version 5.1
<#
.SYNOPSIS
    Initializes the GitHub Copilot workspace for a newly cloned repository.

.DESCRIPTION
    - Injects a project context block into .github/copilot-instructions.md
    - Optionally strips the IR section for non-security engagements
    - Stages and commits the updated instructions file
    - Safe to re-run: replaces existing context block rather than appending

.PARAMETER ProjectName
    Human-readable project name. Used in the context block and commit message.

.PARAMETER Description
    One-sentence description of what this project delivers.

.PARAMETER ProblemStatement
    The problem being solved — current state and desired outcome.

.PARAMETER IsIR
    'yes' to retain the IR/security section. 'no' to strip it.

.EXAMPLE
    pwsh -ExecutionPolicy Bypass -File .vscode/init-copilot.ps1 `
        -ProjectName "GMF - Splunk CIM Normalization" `
        -Description "Normalize IR sourcetypes to CIM schema" `
        -ProblemStatement "Zero normalization exists across 1381 sourcetypes" `
        -IsIR "yes"
#>

param(
    [Parameter(Mandatory)][string]$ProjectName,
    [Parameter(Mandatory)][string]$Description,
    [Parameter(Mandatory)][string]$ProblemStatement,
    [Parameter(Mandatory)][ValidateSet('yes', 'no')][string]$IsIR
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

# ── Resolve paths ──────────────────────────────────────────────────────────────
$repoRoot          = Split-Path -Parent $PSScriptRoot
$instructionsPath  = Join-Path $repoRoot '.github' 'copilot-instructions.md'
$instructionsPath  = [System.IO.Path]::GetFullPath($instructionsPath)

# ── Pre-flight checks ──────────────────────────────────────────────────────────
if (-not (Test-Path $instructionsPath)) {
    Write-Error "copilot-instructions.md not found at expected path:`n  $instructionsPath`n`nEnsure the repo template includes .github/copilot-instructions.md"
    exit 1
}

$gitCheck = git -C $repoRoot rev-parse --is-inside-work-tree 2>&1
if ($LASTEXITCODE -ne 0) {
    Write-Error "Not inside a git repository. Run 'git init' or clone a repo first."
    exit 1
}

# ── Read template ──────────────────────────────────────────────────────────────
Write-Host ""
Write-Host "  Reading instructions template..." -ForegroundColor Cyan
$content = Get-Content $instructionsPath -Raw

# ── Strip IR block if non-security engagement ───────────────────────────────
if ($IsIR -eq 'no') {
    Write-Host "  IR section: DISABLED (non-security engagement)" -ForegroundColor Yellow
    # Removes the block including its surrounding blank lines
    $content = $content -replace '(?s)\r?\n?<!-- IR_START -->.*?<!-- IR_END -->\r?\n?', "`n"
} else {
    Write-Host "  IR section: ENABLED (security engagement)" -ForegroundColor Green
}

# ── Build project context block ────────────────────────────────────────────────
$today = Get-Date -Format 'yyyy-MM-dd'

$contextBlock = @"
<!-- PROJECT_CONTEXT_START -->
## Project Context

> Auto-generated by **Initialize Copilot Workspace** on $today.
> Re-run the task to update. Do not edit the PROJECT_CONTEXT markers manually.

| Field | Value |
|-------|-------|
| **Project** | $ProjectName |
| **Description** | $Description |
| **Problem Statement** | $ProblemStatement |
| **Initialized** | $today |
| **Branch** | $(git -C $repoRoot branch --show-current) |

<!-- PROJECT_CONTEXT_END -->
"@

# ── Inject or replace context block ───────────────────────────────────────────
if ($content -match '<!-- PROJECT_CONTEXT_START -->') {
    Write-Host "  Updating existing project context block..." -ForegroundColor Cyan
    $content = $content -replace '(?s)<!-- PROJECT_CONTEXT_START -->.*?<!-- PROJECT_CONTEXT_END -->', $contextBlock.Trim()
} else {
    Write-Host "  Injecting new project context block..." -ForegroundColor Cyan
    # Preserve any content that was above the first heading
    $content = $contextBlock + "`n`n" + $content.TrimStart()
}

# ── Write file (UTF-8 without BOM) ─────────────────────────────────────────────
Write-Host "  Writing updated instructions file..." -ForegroundColor Cyan
[System.IO.File]::WriteAllText(
    $instructionsPath,
    $content,
    [System.Text.Encoding]::UTF8
)

# ── Stage and commit ───────────────────────────────────────────────────────────
Write-Host "  Staging .github/copilot-instructions.md..." -ForegroundColor Cyan
git -C $repoRoot add '.github/copilot-instructions.md'

$commitMsg = "chore: initialize copilot workspace for $ProjectName"
Write-Host "  Committing: $commitMsg" -ForegroundColor Cyan
git -C $repoRoot commit -m $commitMsg

# ── Success summary ────────────────────────────────────────────────────────────
Write-Host ""
Write-Host "  ✅  Copilot workspace initialized" -ForegroundColor Green
Write-Host ""
Write-Host "  Project   : $ProjectName" -ForegroundColor White
Write-Host "  Branch    : $(git -C $repoRoot branch --show-current)" -ForegroundColor White
Write-Host "  IR     : $IsIR" -ForegroundColor White
Write-Host "  Commit    : $(git -C $repoRoot log --oneline -1)" -ForegroundColor White
Write-Host "  File      : $instructionsPath" -ForegroundColor White
Write-Host ""
Write-Host "  Copilot will now load project context and standing instructions automatically." -ForegroundColor DarkGray
Write-Host ""
